apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dispatch
  namespace: three-tier
  labels: 
    role: dispatch
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: dispatch
  template:
    metadata:
      labels:
        role: dispatch
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: dispatch
        image: public.ecr.aws/j6x4g5g4/dispatch:5ebb805a7a68473410c956794c2ffe01c8bbea8f
        imagePullPolicy: Always
        env:
          - name: AMQP_HOST
            value: rabbitmq
          - name: AMQP_PORT
            value: '5672'