apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: three-tier
  labels:
    role: shipping
    env: demo

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%

  selector:
    matchLabels:
      role: shipping

  template:
    metadata:
      labels:
        role: shipping

    spec:
      containers:
      - name: shipping
        image: robotshop/rs-shipping:latest
        imagePullPolicy: Always

        env:
        - name: MYSQL_HOST
          value: mysql-svc

        - name: MYSQL_DATABASE
          value: cities

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: username

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: password

        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10