apiVersion: apps/v1
kind: Deployment
metadata: 
  name: payment
  namespace: three-tier
  labels: 
    role: payment
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: payment
  template:
    metadata:
      labels:
        role: payment
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: payment
        image: 267580591980.dkr.ecr.us-west-2.amazonaws.com/payment:14043d6cf766f072719f819b52e777171bc09210
        imagePullPolicy: Always
        env:
         - name: AMQP_HOST
           value: rabbitmq
         - name: AMQP_PORT
           value: "5672"
          
