apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: three-tier
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: robotshop/rs-mysql-db:latest

        ports:
        - containerPort: 3306

        resources:
          limits:
              cpu: 100m
              memory: 100Mi
          requests:
              cpu: 50m
              memory: 30Mi