apiVersion: apps/v1
kind: StatefulSet
metadata: 
  namespace: three-tier
  name: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels: 
        app: redis
    spec: 
      containers:
      - name: redis
        image: redis:4.0.6
        ports:
        - containerPort: 6379
        resources:
          limits:
              cpu: 100m
              memory: 100Mi
          requests:
              cpu: 50m
              memory: 30Mi
      restartPolicy: Always

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
